"""criar comunidade model

Revision ID: 07fab699f769
Revises: 7bd7ce483d18
Create Date: 2026-02-18 18:07:23.015338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07fab699f769'
down_revision: Union[str, Sequence[str], None] = '7bd7ce483d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunidades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('nome_slug', sa.String(), nullable=False),
    sa.Column('descricao_curta', sa.String(), nullable=False),
    sa.Column('descricao_longa', sa.String(), nullable=True),
    sa.Column('cor_tema', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('FEIRA', 'MERCADO', 'BAIRRO', 'CONDOMINIO', 'OUTRO', name='tipocomunidade'), nullable=False),
    sa.Column('imagem_url', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comunidades_nome_slug'), 'comunidades', ['nome_slug'], unique=True)
    op.add_column('vendedores', sa.Column('comunidade_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_vendedores_comunidade_id'), 'vendedores', ['comunidade_id'], unique=False)
    op.create_foreign_key(None, 'vendedores', 'comunidades', ['comunidade_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendedores', type_='foreignkey')
    op.drop_index(op.f('ix_vendedores_comunidade_id'), table_name='vendedores')
    op.drop_column('vendedores', 'comunidade_id')
    op.drop_index(op.f('ix_comunidades_nome_slug'), table_name='comunidades')
    op.drop_table('comunidades')
    # ### end Alembic commands ###
