"""coluna 'ativo' para usuarios

Revision ID: 310995fba177
Revises: 3c7490ee00f9
Create Date: 2026-02-16 11:30:39.451674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310995fba177'
down_revision: Union[str, Sequence[str], None] = '3c7490ee00f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('ativo', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'ativo')
    # ### end Alembic commands ###
