"""criar tabela vendedores

Revision ID: 3c7490ee00f9
Revises: b7a66745cf14
Create Date: 2026-02-16 10:59:45.135186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c7490ee00f9'
down_revision: Union[str, Sequence[str], None] = 'b7a66745cf14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendedores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=False),
    sa.Column('nome_fantasia_slug', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('chave_pix', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendedores_nome_fantasia_slug'), 'vendedores', ['nome_fantasia_slug'], unique=True)
    op.create_index(op.f('ix_vendedores_usuario_id'), 'vendedores', ['usuario_id'], unique=False)
    op.create_table('horarios_funcionamento',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendedor_id', sa.String(), nullable=False),
    sa.Column('dia_semana', sa.Enum('DOMINGO', 'SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO', name='diasemana'), nullable=False),
    sa.Column('hora_inicio', sa.String(), nullable=False),
    sa.Column('hora_fim', sa.String(), nullable=False),
    sa.Column('todo_tempo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horarios_funcionamento')
    op.drop_index(op.f('ix_vendedores_usuario_id'), table_name='vendedores')
    op.drop_index(op.f('ix_vendedores_nome_fantasia_slug'), table_name='vendedores')
    op.drop_table('vendedores')
    # ### end Alembic commands ###
