"""criar produtos e produtos_vendedores models

Revision ID: 52f459e686aa
Revises: 07fab699f769
Create Date: 2026-02-20 20:04:42.585999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f459e686aa'
down_revision: Union[str, Sequence[str], None] = '07fab699f769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('unidade_medida', sa.Enum('KG', 'UNIDADE', 'LITRO', 'PACOTE', 'CAIXA', 'MACO', 'FARDO', 'BANDEJA', name='tipounidade'), nullable=False),
    sa.Column('imagem_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos_vendedores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendedor_id', sa.String(), nullable=False),
    sa.Column('produto_id', sa.String(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DISPONIVEL', 'INDISPONIVEL', 'ESGOTADO', name='statusproduto'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos_vendedores')
    op.drop_table('produtos')
    # ### end Alembic commands ###
