"""criar pedidos

Revision ID: 9084811d3fe6
Revises: a7fb6f5126b3
Create Date: 2026-03-28 17:31:15.018976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9084811d3fe6'
down_revision: Union[str, Sequence[str], None] = 'a7fb6f5126b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=False),
    sa.Column('vendedor_id', sa.String(), nullable=False),
    sa.Column('comunidade_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADO', 'RECUSADO', 'ENTREGUE', name='statuspedido'), nullable=False),
    sa.Column('motivo_recusa', sa.String(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('aprovado_em', sa.DateTime(), nullable=True),
    sa.Column('recusado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['comunidade_id'], ['comunidades.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_cliente_id'), 'pedidos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pedidos_comunidade_id'), 'pedidos', ['comunidade_id'], unique=False)
    op.create_index(op.f('ix_pedidos_status'), 'pedidos', ['status'], unique=False)
    op.create_index(op.f('ix_pedidos_vendedor_id'), 'pedidos', ['vendedor_id'], unique=False)
    op.create_table('pedido_itens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pedido_id', sa.String(), nullable=False),
    sa.Column('produto_vendedor_id', sa.String(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total_item', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['produto_vendedor_id'], ['produtos_vendedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_itens_pedido_id'), 'pedido_itens', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_pedido_itens_produto_vendedor_id'), 'pedido_itens', ['produto_vendedor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_itens_produto_vendedor_id'), table_name='pedido_itens')
    op.drop_index(op.f('ix_pedido_itens_pedido_id'), table_name='pedido_itens')
    op.drop_table('pedido_itens')
    op.drop_index(op.f('ix_pedidos_vendedor_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_status'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_comunidade_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_cliente_id'), table_name='pedidos')
    op.drop_table('pedidos')
    # ### end Alembic commands ###
