"""criando tabela endereco

Revision ID: a7fb6f5126b3
Revises: d23bbd641b7f
Create Date: 2026-03-14 17:22:11.051344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7fb6f5126b3'
down_revision: Union[str, Sequence[str], None] = 'd23bbd641b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enderecos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.Column('comunidade_id', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('rua', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['comunidade_id'], ['comunidades.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enderecos_comunidade_id'), 'enderecos', ['comunidade_id'], unique=False)
    op.create_index(op.f('ix_enderecos_usuario_id'), 'enderecos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enderecos_usuario_id'), table_name='enderecos')
    op.drop_index(op.f('ix_enderecos_comunidade_id'), table_name='enderecos')
    op.drop_table('enderecos')
    # ### end Alembic commands ###
