"""usuario cadastro simplificado

Revision ID: c6f87775ef06
Revises: 9084811d3fe6
Create Date: 2026-03-29 20:01:18.539640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f87775ef06'
down_revision: Union[str, Sequence[str], None] = '9084811d3fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('cadastro_completo', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.drop_index(op.f('ix_usuarios_telefone'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_telefone'), 'usuarios', ['telefone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_telefone'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_telefone'), 'usuarios', ['telefone'], unique=False)
    op.drop_column('usuarios', 'cadastro_completo')
    # ### end Alembic commands ###
